### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by metaflow** [metaflow/apex-recoil#1]
Click on emojis or leave feedback here ❤️.

If you have an issue or a concrete idea of improvement, please [create a new bug](https://github.com/metaflow/apex-recoil/issues/new/choose) to discuss. Don't expect anything to be implemented or fixed though, I do this at my leisure 🏖️.

☮️ [Respect each other](https://github.com/metaflow/apex-recoil/blob/main/docs/code-of-conduct.md).

**Comment by kelyar** [comment]
thanks, looks really good

**Comment by SkywalkerJi** [comment]
Can you add a option for vertical scale？
lv.1 95%
https://apexlegends.fandom.com/wiki/Attachment

**Comment by metaflow** [comment]
HI @SkywalkerJi ! for the vertical scale - do you mean to decrease the recoil proportionally depending on the attachment level? I have removed the attachment selection soon after the first version: as patterns are basically the same and have no random component. Also, I am not sure if attachment selection really adds any value to the practice: if one is so good that they can spot 5% difference in size then I don't think they should use this app anymore and spend time on other aspects of the game 😃 

> I want to know the recoil pattern on the webpage is the same as the 1x scope or Hipfire?

Recoils are for 1x scope (any scope really as they don't depend on scope magnification). Hipfire recoils are way too erratic and random. So you need to plug your ("sensitivity" * "ads") as a sensitivity option (usually ads = 1).

thank you for the https://www.gtnprn.com/summary_apex_recoil reference! Looks like a great resource.

**Comment by SkywalkerJi** [comment]
How do I  update L-STAR, Prowler SMG  burst and Rampage.

By the way，Is there any plan to support Rampart's passive？

**Comment by metaflow** [comment]
@SkywalkerJi I am planning to update weapons this weekend.
> Is there any plan to support Rampart's passive？
no, why?
