### ISSUE TITLE
Can u tell how to calculate pixel using angle values?

### ISSUE THREAD

**Issue by Santosh0088** [metaflow/apex-recoil#12]
Please check existing issues https://github.com/metaflow/apex-recoil/issues first.
Include your browser version and platform in case of rendering issues.
-----------
Bro can please tell how to calculate pixel values using angle values so that i can get other weapon recoil patterns

**Comment by metaflow** [comment]
good idea, I was also thinking that it might be good to document that.

**Comment by metaflow** [comment]
see https://github.com/metaflow/apex-recoil/blob/main/docs/capture.md

**Comment by Santosh0088** [comment]
Thank you so much sir! Lots of love for you!😍❤❤❤
