### ISSUE TITLE
How to add new recoil patterns ℹ️ 

### ISSUE THREAD

**Issue by metaflow** [metaflow/apex-recoil#2]
Greetings traveler! It seems that you are the first one who wants to contribute a recoil pattern 🥇 . It's a bit convoluted process so I didn't bother to document it unless someone actually needs that. Please comment below if you would like to spend some time on this adventure 🗺️.

**Comment by Lyxica** [comment]
I'm interested in adding the l star pattern

**Comment by metaflow** [comment]
@Lyxica thank you for the offer. I was about to write you that it would be really hard (as lstar does not leave clear marks on the walls) and tried to mark them anyway. Turned out it's wasn't that hard 😄 I've added lstar pattern. So now we have a complete collection.

**Comment by metaflow** [comment]
Closing as all weapons are encoded.
