### ISSUE TITLE
Windows sensitivity is not 6/11

### ISSUE THREAD

**Issue by Tempo7an** [metaflow/apex-recoil#3]
my Windows sensitivity is 5/11, in-game is 1.6 and mouse dpi is 1800
how do I calculate the sensitivity to use on this app?

**Comment by metaflow** [comment]
Simply multiply the windows factor by in-game. So, in your case: 5/11 sensitivity is 0.8 (according to https://liquipedia.net/counterstrike/Mouse_Settings#Windows_Sensitivity), 0.8 * 1.6 = 1.28 - that's the number you should use for the "sensitivity" in the app.

**Comment by Tempo7an** [comment]
a little confused on "So for very small sensitivity in windows, we should get smaller patterns" with slower mouse, shouldn't the pattern be bigger?
anyways thanks!

**Comment by metaflow** [comment]
@Tempo7 to rotate by fixed number of degress in game:

(constant degrees) = (mouse physical distance) * sensitivity * CPI * (another constant)

(mouse physical distance) = (constant) / (sensitivity * CPI)

Lenght of the interval in browser:

(length in browser) = (mouse physical distance) * (windows sensitivity) * CPI = (constant) * (windows sensitivitiy) / (sensitivity)

So you can simulate decrease in windows sensitivity by increasing "sensitivity" proportionally.
